version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      timezone: America/Los_Angeles
      interval: weekly
    commit-message:
      prefix: 👷
  - package-ecosystem: gomod
    directory: /
    schedule:
      timezone: America/Los_Angeles
      interval: weekly
    commit-message:
      prefix: ⬆
